### PR TITLE
INFRA-1522 helm logs

### PR DESCRIPTION
**Pull request by snarfmonkey**
It's so crazy it just might work. 

This is two ideas in one.

I added the helm-github plugin in the hopes that we can ditch chartmuseum because then we won't have to host it anywhere. Nice.

To do this I added a bit in the action that installs plugins. Annoying that we have to pass in an array as a string in the inputs, but whatever. 

I'm also not sure if I accomplished anything by including the plugin code. I was hoping to "install it locally" but the install script in that repo makes me think it still grabs the tarball from them. 

Then there is the helm_upgrade_logs script I stole from this [ruby gem](https://gitlab.com/samuel-garratt/helm_upgrade_logs). I added the ability for it to filter on namespace and version, so the returned events/logs are not mixed in with already running pods.  It's not an awesome script, but it might help people more easily see why a GHA pipeline deploy didn't work. 

There is one thing it didn't like involving the api version of the authentication plugin, so that might need ironing out. We should, in theory, be using the AWS command to get our kubeconfig.

### CODE REVIEW

**Comment by snarfmonkey** [comment]
I could use some help with the script. It clearly needs:
- to exit properly on failure so the github action doesn't run indefinitely

stretch goals:
- better newlines
- maybe to not even rely on this mess of github actions, docker builds, and pip installs somehow and be simplified into a single script or docker image we host? IDK

but this is almost there: https://github.com/hinge-health/demo-service/runs/6564391015?check_suite_focus=true

**Comment by jghowe** [comment]
A few questions, this was a fork of a public, Github marketplace action.  It seems like the updates you made could be used by other outside our org but want to verify?  I assume the `helm-github` command needs permission to read from the releases of a private repo so is that working okay?  Also once we verify this works let's update the README with the new features.

**Comment by snarfmonkey** [comment]
Oh dear. I think only the plugin-addition part is worth porting back upstream. That logs bit gets very specific to what we're trying to accomplish, I think, since the script assumes we're using helm 3 and has IMAGE_TAG in the environment (which is only necessarily true for our workflow).

Should we unfork this and make it our pet or should I make a PR that is only for the plugins part? Adding plugins seems like a reasonable addition, though whatever people have to do to support their specific plugin in their workflow will probably be on them.

**Comment by jghowe** [comment]
I suppose it depends on how much work it would take to make the approach more generic.  So maybe we keep this fork as our pet project for now and we can follow up with future revisions to make it more useable by others and then come out with a nice blog post or something to promote. 😄

**Comment by snarfmonkey** [comment]
This will have to be our baby for now. I have some links to demo-service workflows demonstrating it.

**Pull request merged**
